[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flaskr"
version = "0.1.0"
dependencies = [
  "flask",
]

[tool.setuptools.packages.find]
include = ["flaskr"]
exclude = ["instance"]
